spring:
  profiles:
    active: dev

##document properties
document:
#  base-path: ./resources
#  aws-s3-base-url: ${S3_BASE_URL} #used for s3
  aws-s3-folder: test/ #s3 base folder with final /
#  aws-s3-base-env-folder: ${spring.profiles.active} #s3 base folder without final /


#SDK info used for S3 integration
aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID} #access key ID
      secret: ${AWS_ACCESS_KEY_SECRET}#key secret

#S3 integration info
s3:
  region:
    name: ${S3_REGION} #region
  bucket:
    name: ${S3_BUCKET} #bucket name

##Cognito integration info
#com:
#  kb:
#    jwt:
#      aws:
#        userPoolId: #user pool id
#        region: #user pool region




